/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.*;
import net.proteanit.sql.DbUtils;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import java.awt.Desktop;
import java.io.File;
import java.lang.Object; 
import java.nio.channels.FileChannel;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;
import java.io.FileOutputStream;
import java.text.DecimalFormat;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import com.itextpdf.text.Image;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Adi
 */
public class welcome3 extends javax.swing.JFrame {

    static Connection conn = loginGUI.conn;
    static PreparedStatement pst = null;
    static ResultSet rs = null;
    public String filename_supplier;
    public String supplier_filename_update;
    public String supplier_filename_show_contract;
    public String filename_show_report;
    public String sn; 
    public String fn;
    String tableClick;
    String searchmethod;
    String oq;
    String iid;
    

    /**
     * Creates new form welcome
     */
    public welcome3() {

        initComponents();
        reportsTab.setVisible(false);
        usersTab.setVisible(false);
        AlertIcon.setVisible(false);
        QuantityChangeButton.setEnabled(false);
        
       
        int check=0;
        try{
         String sql = "select flag from users where user_type=3";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                check=rs.getInt("flag");
            }
            if(check==1){
               AlertIcon.setVisible(true);
               QuantityChangeButton.setEnabled(true);
               }  
            } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchGroup = new javax.swing.ButtonGroup();
        SupplierButtonGroup = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        projectsButton = new javax.swing.JButton();
        reportsButton = new javax.swing.JButton();
        usersButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        projectsTab = new javax.swing.JTabbedPane();
        AddProjectPanel = new javax.swing.JPanel();
        projIDtxt = new javax.swing.JTextField();
        projNametxt = new javax.swing.JTextField();
        projStartDate = new com.toedter.calendar.JDateChooser();
        projDueDate = new com.toedter.calendar.JDateChooser();
        jScrollPane13 = new javax.swing.JScrollPane();
        projDesctxt = new javax.swing.JTextArea();
        projAddButton = new javax.swing.JButton();
        projClearButton = new javax.swing.JButton();
        ProjectIDLabel = new javax.swing.JLabel();
        ProjectNameLabel = new javax.swing.JLabel();
        ProjectStartdateLabel = new javax.swing.JLabel();
        ProjectDuedateLabel = new javax.swing.JLabel();
        ProjectCommentsLabel = new javax.swing.JLabel();
        background_green11 = new javax.swing.JLabel();
        StatusProjectPanel = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        projUpTable = new javax.swing.JTable();
        projUpDueDate = new com.toedter.calendar.JDateChooser();
        projUpStatusChoice = new java.awt.Choice();
        projUpStatusButton = new javax.swing.JButton();
        projUpRefreshButton = new javax.swing.JButton();
        projUpSearchButton = new javax.swing.JButton();
        projSearchUptxt = new javax.swing.JTextField();
        projNameRadioButton = new javax.swing.JRadioButton();
        projIDRadioButton = new javax.swing.JRadioButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        projComUptxt = new javax.swing.JTextArea();
        EnterYourSearchLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        background_green12 = new javax.swing.JLabel();
        SearchProjectPanel = new javax.swing.JPanel();
        projSearchtxt = new javax.swing.JTextField();
        projSearchButton = new javax.swing.JButton();
        projNameRadioButton1 = new javax.swing.JRadioButton();
        projIDRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        projSearchTable = new javax.swing.JTable();
        projRefreshSearchButton = new javax.swing.JButton();
        EnterYourSearchLabel10 = new javax.swing.JLabel();
        background_green13 = new javax.swing.JLabel();
        reportsTab = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        monthRepjSpin = new com.toedter.components.JSpinField();
        yearRepjSpin = new com.toedter.components.JSpinField();
        repItemIDtxt = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        background_green14 = new javax.swing.JLabel();
        HistoryPanel = new javax.swing.JPanel();
        background_green16 = new javax.swing.JLabel();
        ProjectReportPanel = new javax.swing.JPanel();
        genRepButton = new javax.swing.JToggleButton();
        pBeginDateChooser = new com.toedter.calendar.JDateChooser();
        pEndDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Show_report_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        background_green15 = new javax.swing.JLabel();
        usersTab = new javax.swing.JTabbedPane();
        AddUserPanel = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        AddUserTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        WorkerDetailsLabel = new javax.swing.JLabel();
        UserFirstNameLabel = new javax.swing.JLabel();
        UserFirstNameText = new javax.swing.JTextField();
        UserLastNameText = new javax.swing.JTextField();
        UserLastNameLabel = new javax.swing.JLabel();
        UserPhoneLabel = new javax.swing.JLabel();
        UserPhoneText = new javax.swing.JTextField();
        UserJobTitleText = new javax.swing.JTextField();
        UserJobTitleLabel = new javax.swing.JLabel();
        UserEmailText = new javax.swing.JTextField();
        UserEmailLabel = new javax.swing.JLabel();
        UserAddButton = new javax.swing.JButton();
        UserClearButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        UserDetailsLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        UserNameText = new javax.swing.JTextField();
        UserPasswordLabel = new javax.swing.JLabel();
        UserPasswordText = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        UserPermissionLabel = new javax.swing.JLabel();
        UserPermissionChoise = new java.awt.Choice();
        background_green4 = new javax.swing.JLabel();
        AlertIcon = new javax.swing.JLabel();
        QuantityChangeButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setPreferredSize(new java.awt.Dimension(55, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 222, 1240, 10));

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1223, 4, 55, 20));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1153, 4, 30, 20));

        projectsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Projects icon 53 x 50.png"))); // NOI18N
        projectsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(projectsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 65, 60));

        reportsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reports icon 53 x 50.png"))); // NOI18N
        reportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(reportsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 65, 60));

        usersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Users icon 53 x 50.png"))); // NOI18N
        usersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersButtonActionPerformed(evt);
            }
        });
        getContentPane().add(usersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 65, -1));

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout button.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 30, 30));

        projectsTab.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        projectsTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectsTabMouseClicked(evt);
            }
        });

        AddProjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        AddProjectPanel.add(projIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 118, -1));
        AddProjectPanel.add(projNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 120, -1));

        projStartDate.setDateFormatString("yyyy-MM-dd");
        projStartDate.setMinSelectableDate(new Date());
        AddProjectPanel.add(projStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 127, -1));

        projDueDate.setMinSelectableDate(new Date());
        AddProjectPanel.add(projDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 127, -1));

        projDesctxt.setColumns(20);
        projDesctxt.setRows(5);
        jScrollPane13.setViewportView(projDesctxt);

        AddProjectPanel.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 130, -1));

        projAddButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        projAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus_icon.png"))); // NOI18N
        projAddButton.setText("Add");
        projAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projAddButtonActionPerformed(evt);
            }
        });
        AddProjectPanel.add(projAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        projClearButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        projClearButton.setText("Clear");
        projClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projClearButtonActionPerformed(evt);
            }
        });
        AddProjectPanel.add(projClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 100, 40));

        ProjectIDLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ProjectIDLabel.setText("Project ID");
        AddProjectPanel.add(ProjectIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        ProjectNameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ProjectNameLabel.setText("Project Name");
        AddProjectPanel.add(ProjectNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        ProjectStartdateLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ProjectStartdateLabel.setText("Start Date");
        AddProjectPanel.add(ProjectStartdateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        ProjectDuedateLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ProjectDuedateLabel.setText("Due Date");
        AddProjectPanel.add(ProjectDuedateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        ProjectCommentsLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ProjectCommentsLabel.setText("Comments");
        AddProjectPanel.add(ProjectCommentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        background_green11.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        background_green11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        AddProjectPanel.add(background_green11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 430));

        projectsTab.addTab("Add Project", AddProjectPanel);

        StatusProjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        projUpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        projUpTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projUpTableMouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(projUpTable);

        StatusProjectPanel.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 800, 220));

        projUpDueDate.setMinSelectableDate(new Date());
        StatusProjectPanel.add(projUpDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 140, -1));

        projUpStatusChoice.addItem("Pending");
        projUpStatusChoice.addItem("In Progress");
        projUpStatusChoice.addItem("Completed");
        StatusProjectPanel.add(projUpStatusChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 100, -1));

        projUpStatusButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        projUpStatusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save-icon-30.png"))); // NOI18N
        projUpStatusButton.setText("Update");
        projUpStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projUpStatusButtonActionPerformed(evt);
            }
        });
        StatusProjectPanel.add(projUpStatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 250, -1, -1));

        projUpRefreshButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        projUpRefreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        projUpRefreshButton.setText("Refresh");
        projUpRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projUpRefreshButtonActionPerformed(evt);
            }
        });
        StatusProjectPanel.add(projUpRefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, -1, -1));

        projUpSearchButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        projUpSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        projUpSearchButton.setText("Search");
        projUpSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projUpSearchButtonActionPerformed(evt);
            }
        });
        StatusProjectPanel.add(projUpSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));
        StatusProjectPanel.add(projSearchUptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        searchGroup.add(projNameRadioButton);
        projNameRadioButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        projNameRadioButton.setText("By Name");
        projNameRadioButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        projNameRadioButton.setBorderPainted(true);
        projNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projNameRadioButtonActionPerformed(evt);
            }
        });
        StatusProjectPanel.add(projNameRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, -1));

        searchGroup.add(projIDRadioButton);
        projIDRadioButton.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        projIDRadioButton.setText("By ID");
        projIDRadioButton.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        projIDRadioButton.setBorderPainted(true);
        projIDRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projIDRadioButtonActionPerformed(evt);
            }
        });
        StatusProjectPanel.add(projIDRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        projComUptxt.setColumns(20);
        projComUptxt.setRows(5);
        jScrollPane15.setViewportView(projComUptxt);

        StatusProjectPanel.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 130, -1));

        EnterYourSearchLabel9.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        EnterYourSearchLabel9.setText("Enter your search");
        StatusProjectPanel.add(EnterYourSearchLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel22.setText(" Due Date");
        StatusProjectPanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel23.setText("Project Status");
        StatusProjectPanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel24.setText("Comments");
        StatusProjectPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        background_green12.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        background_green12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        StatusProjectPanel.add(background_green12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 430));

        projectsTab.addTab(" Status", StatusProjectPanel);

        SearchProjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        SearchProjectPanel.add(projSearchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        projSearchButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        projSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        projSearchButton.setText("Search");
        projSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projSearchButtonActionPerformed(evt);
            }
        });
        SearchProjectPanel.add(projSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        searchGroup.add(projNameRadioButton1);
        projNameRadioButton1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        projNameRadioButton1.setText("By Name");
        projNameRadioButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projNameRadioButton1.setBorderPainted(true);
        projNameRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projNameRadioButton1ActionPerformed(evt);
            }
        });
        SearchProjectPanel.add(projNameRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 90, -1));

        searchGroup.add(projIDRadioButton1);
        projIDRadioButton1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        projIDRadioButton1.setText("By ID");
        projIDRadioButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        projIDRadioButton1.setBorderPainted(true);
        projIDRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projIDRadioButton1ActionPerformed(evt);
            }
        });
        SearchProjectPanel.add(projIDRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        projSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane16.setViewportView(projSearchTable);

        SearchProjectPanel.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 800, 220));

        projRefreshSearchButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        projRefreshSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        projRefreshSearchButton.setText("Refresh");
        projRefreshSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projRefreshSearchButtonActionPerformed(evt);
            }
        });
        SearchProjectPanel.add(projRefreshSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 250, -1, -1));

        EnterYourSearchLabel10.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        EnterYourSearchLabel10.setText("Enter your search");
        SearchProjectPanel.add(EnterYourSearchLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        background_green13.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        background_green13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        SearchProjectPanel.add(background_green13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 430));

        projectsTab.addTab("Search", SearchProjectPanel);

        reportsTab.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jButton2.setText("Bar Graph");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        monthRepjSpin.setMaximum(12);
        monthRepjSpin.setMinimum(1);
        monthRepjSpin.setValue(1);
        jPanel14.add(monthRepjSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 44, -1));

        yearRepjSpin.setMinimum(2000);
        yearRepjSpin.setValue(2000);
        jPanel14.add(yearRepjSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));
        jPanel14.add(repItemIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 78, -1));
        jPanel14.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));
        jPanel14.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        background_green14.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        background_green14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        jPanel14.add(background_green14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        reportsTab.addTab("Generate", jPanel14);

        HistoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background_green16.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        background_green16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        HistoryPanel.add(background_green16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 430));

        reportsTab.addTab("History", HistoryPanel);

        ProjectReportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genRepButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        genRepButton.setText("Generate Report");
        genRepButton.setOpaque(true);
        genRepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genRepButtonActionPerformed(evt);
            }
        });
        ProjectReportPanel.add(genRepButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, 50));

        pBeginDateChooser.setDateFormatString("yyyy-MM-dd");
        ProjectReportPanel.add(pBeginDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 130, -1));

        pEndDateChooser.setDateFormatString("yyyy-MM-dd");
        ProjectReportPanel.add(pEndDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel2.setText("This report shows all projects from two chosen dates.");
        ProjectReportPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setText("You can see the report by clicking on this button ");
        ProjectReportPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel6.setText("In order to start, please chose a start date ");
        ProjectReportPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel7.setText("Chose a due date");
        ProjectReportPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        Show_report_Button.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        Show_report_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icon-service-contract.png"))); // NOI18N
        Show_report_Button.setText("Show Report");
        Show_report_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_report_ButtonActionPerformed(evt);
            }
        });
        ProjectReportPanel.add(Show_report_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 190, 40));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel8.setText("Click on this button");
        ProjectReportPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        background_green15.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        background_green15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        ProjectReportPanel.add(background_green15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 430));

        reportsTab.addTab("Project Report", ProjectReportPanel);

        usersTab.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        usersTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTabMouseClicked(evt);
            }
        });

        AddUserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AddUserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserTableMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(AddUserTable);

        AddUserPanel.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 800, 220));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WorkerDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        WorkerDetailsLabel.setText("Worker Details");
        jPanel1.add(WorkerDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        UserFirstNameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserFirstNameLabel.setText("First Name");
        jPanel1.add(UserFirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        UserFirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFirstNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(UserFirstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, -1));

        UserLastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLastNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(UserLastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 130, -1));

        UserLastNameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserLastNameLabel.setText("Last Name");
        jPanel1.add(UserLastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        UserPhoneLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserPhoneLabel.setText("Phone");
        jPanel1.add(UserPhoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, -1));

        UserPhoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPhoneTextActionPerformed(evt);
            }
        });
        jPanel1.add(UserPhoneText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, -1));

        UserJobTitleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserJobTitleTextActionPerformed(evt);
            }
        });
        jPanel1.add(UserJobTitleText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));

        UserJobTitleLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserJobTitleLabel.setText("Job Title");
        jPanel1.add(UserJobTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, -1));

        UserEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEmailTextActionPerformed(evt);
            }
        });
        jPanel1.add(UserEmailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, -1));

        UserEmailLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserEmailLabel.setText("Email");
        jPanel1.add(UserEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, -1));

        AddUserPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 260));

        UserAddButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        UserAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus_icon.png"))); // NOI18N
        UserAddButton.setText("Add");
        UserAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserAddButtonActionPerformed(evt);
            }
        });
        AddUserPanel.add(UserAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, -1, -1));

        UserClearButton.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        UserClearButton.setText("Clear");
        UserClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserClearButtonActionPerformed(evt);
            }
        });
        AddUserPanel.add(UserClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 110, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserDetailsLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        UserDetailsLabel.setText("Fill User Details");
        jPanel2.add(UserDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        UserNameLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserNameLabel.setText("Username");
        jPanel2.add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        UserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameTextActionPerformed(evt);
            }
        });
        jPanel2.add(UserNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        UserPasswordLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserPasswordLabel.setText("Password");
        jPanel2.add(UserPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        UserPasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPasswordTextActionPerformed(evt);
            }
        });
        jPanel2.add(UserPasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, -1));

        jLabel43.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 0, 0));
        jLabel43.setText("Password Must be 6 letters at least ");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        UserPermissionLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        UserPermissionLabel.setText("Permission Level");
        jPanel2.add(UserPermissionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        UserPermissionChoise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserPermissionChoiseMouseClicked(evt);
            }
        });
        jPanel2.add(UserPermissionChoise, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, -1));
        UserPermissionChoise.addItem("0");
        UserPermissionChoise.addItem("1");
        UserPermissionChoise.addItem("2");
        UserPermissionChoise.addItem("3");

        AddUserPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 480, 140));

        background_green4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/background.png"))); // NOI18N
        AddUserPanel.add(background_green4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1250, 470));

        usersTab.addTab("Add User", AddUserPanel);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(projectsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(usersTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(projectsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(reportsTab, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(usersTab, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(projectsTab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(reportsTab, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(usersTab, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 1240, 430));

        AlertIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/applet-critical-48.png"))); // NOI18N
        getContentPane().add(AlertIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, -1, -1));

        QuantityChangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Quantity Change icon 53x50.png"))); // NOI18N
        QuantityChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityChangeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(QuantityChangeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 65, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 40));
        jLabel9.setText(loginGUI.username+" Is Logged in");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/מסך רקע ראשי מתוקן.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.setState(welcome3.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        this.setVisible(false);
        loginGUI lg = new loginGUI(1);
        lg.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void projectsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsButtonActionPerformed
        projectsTab.setVisible(true);
        reportsTab.setVisible(false);
        usersTab.setVisible(false);
    }//GEN-LAST:event_projectsButtonActionPerformed

    private void projAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projAddButtonActionPerformed
        int f = 0;
        int h = 0;       
        try {
            String sql = "Insert into projects (project_id,project_name,start_date,due_date,comments) values(?,?,?,?,?)";

            pst = conn.prepareStatement(sql);
            pst.setString(1, projIDtxt.getText());
            pst.setString(2, projNametxt.getText());
            pst.setDate(3, new java.sql.Date(projStartDate.getDate().getTime()));
            pst.setDate(4, new java.sql.Date(projDueDate.getDate().getTime()));
            pst.setString(6, projDesctxt.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Project Added");
        } catch (Exception e) {
            h = 1;
            
            if (projIDtxt.getText().isEmpty())
                projIDtxt.setBackground(Color.red);
            else projIDtxt.setBackground(Color.white);
            
            if (projNametxt.getText().isEmpty())
                projNametxt.setBackground(Color.red);
            else projNametxt.setBackground(Color.white);
           
            if (projDesctxt.getText().isEmpty()) 
                projDesctxt.setBackground(Color.red);
            else projDesctxt.setBackground(Color.white);
            
            if (f != 2) {
                JOptionPane.showMessageDialog(null, "The Marked Fields Are Empty\n Please Fill All Fields");
            } else {
                JOptionPane.showMessageDialog(null, e);
            }
        }

        if (f == 0 && h==0) {
            projIDtxt.setText("");
            projNametxt.setText("");
            projDesctxt.setText("");
            projStartDate.setCalendar(null);
            projDueDate.setCalendar(null);
        }
    }//GEN-LAST:event_projAddButtonActionPerformed

    private void projClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projClearButtonActionPerformed
            projIDtxt.setText("");
            projNametxt.setText("");
            projDesctxt.setText("");
            projStartDate.setCalendar(null);
            projDueDate.setCalendar(null);
    }//GEN-LAST:event_projClearButtonActionPerformed

    private void projIDRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projIDRadioButtonActionPerformed
        searchmethod="proj_id";
    }//GEN-LAST:event_projIDRadioButtonActionPerformed

    private void projNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projNameRadioButtonActionPerformed
       searchmethod="proj_name";
    }//GEN-LAST:event_projNameRadioButtonActionPerformed

    private void projectsTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectsTabMouseClicked
        update_Status_ProjTable();
        update_Search_ProjTable();
    }//GEN-LAST:event_projectsTabMouseClicked

    private void projUpSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projUpSearchButtonActionPerformed
         if(searchmethod.equals("project_id"))
        {
        try {
            String sn=projSearchUptxt.getText();
            String sql = "select project_id as 'Project ID',project_name as 'Project Name',start_date as 'Start Date',due_date as 'Due Date',status as 'Status',comments as 'Comments' from projects where project_id='"+sn+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            projUpTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else{
            try {
            String sn=projSearchUptxt.getText();
            String sql = "select project_id as 'Project ID',project_name as 'Project Name',start_date as 'Start Date',due_date as 'Due Date',status as 'Status',comments as 'Comments' from projects where project_name='"+sn+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            projUpTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_projUpSearchButtonActionPerformed

    private void projUpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projUpTableMouseClicked
         try {
            int raw = projUpTable.getSelectedRow();
            tableClick = (projUpTable.getModel().getValueAt(raw, 0).toString());
            String sql = "select due_date,status,comments from projects where project_id='" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                Date add1 = rs.getDate("due_date");
                projUpDueDate.setDate(add1);
                String add2 = rs.getString("status");
                projUpStatusChoice.select(add2);
                String add3 = rs.getString("comments");
                projComUptxt.setText(add3);
              
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_projUpTableMouseClicked

    private void projUpStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projUpStatusButtonActionPerformed
        try{

            String vs = projUpStatusChoice.getSelectedItem();
            String vq = projComUptxt.getText();
            Date vd =  new java.sql.Date(projUpDueDate.getDate().getTime());
          

            String sql = "update projects set status='"+vs+"',comments='"+vq+"',due_date='"+vd+"' where item_id='"+tableClick+"'";

            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Item Updated");
            update_Status_ProjTable();
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_projUpStatusButtonActionPerformed

    private void projUpRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projUpRefreshButtonActionPerformed
        update_Status_ProjTable();
        
    }//GEN-LAST:event_projUpRefreshButtonActionPerformed

    private void projSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projSearchButtonActionPerformed
         if(searchmethod.equals("project_id"))
        {
        try {
            String sn=projSearchtxt.getText();
            String sql = "select project_id as 'Project ID',project_name as 'Project Name',start_date as 'Start Date',due_date as 'Due Date',status as 'Status',comments as 'Comments' from projects where project_id='"+sn+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            projSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        else{
            try {
            String sn=projSearchtxt.getText();
            String sql = "select project_id as 'Project ID',project_name as 'Project Name',start_date as 'Start Date',due_date as 'Due Date',status as 'Status',comments as 'Comments' from projects where project_name='"+sn+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            projSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_projSearchButtonActionPerformed

    private void projNameRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projNameRadioButton1ActionPerformed
       searchmethod="proj_name";
    }//GEN-LAST:event_projNameRadioButton1ActionPerformed

    private void projIDRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projIDRadioButton1ActionPerformed
       searchmethod="proj_id";
    }//GEN-LAST:event_projIDRadioButton1ActionPerformed

    private void projRefreshSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projRefreshSearchButtonActionPerformed
        update_Search_ProjTable();
    }//GEN-LAST:event_projRefreshSearchButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int month = monthRepjSpin.getValue();
        int year= yearRepjSpin.getValue();
        int qt=0,subSum=0;
        try{
        String sql="select quantity_trace,MAX(date) from quantity where MONTH(date)='"+month+"'and YEAR(date)='"+year+"'and item_id='"+repItemIDtxt.getText()+"'";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        rs.next();
        qt=rs.getInt("quantity_trace");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        try{
        String sql="select sum(amount_for_operation) as asum from quantity where operation_type='Subtract' and MONTH(date)='"+month+"'and YEAR(date)='"+year+"'and item_id='"+repItemIDtxt.getText()+"'";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        rs.next();
        subSum=rs.getInt("asum");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        DefaultCategoryDataset dataSet = new DefaultCategoryDataset();
        dataSet.setValue(qt,"Values","Quantity" );
        dataSet.setValue(subSum,"Values","SubItemes" );
        
        JFreeChart chart = ChartFactory.createBarChart3D("Values", "Quantity","Parameters", dataSet, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.CYAN);
        chart.getTitle().setPaint(Color.RED);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.GREEN);
        ChartFrame frame = new ChartFrame("Chart",chart);
        frame.setVisible(true);
        frame.setSize(450,350);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsButtonActionPerformed
        projectsTab.setVisible(false);
        reportsTab.setVisible(true);
        usersTab.setVisible(false);
    }//GEN-LAST:event_reportsButtonActionPerformed

    private void usersTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTabMouseClicked
        user_update_table();
    }//GEN-LAST:event_usersTabMouseClicked

    private void AddUserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserTableMouseClicked
            
        try {
            int raw = AddUserTable.getSelectedRow();
            tableClick = (AddUserTable.getModel().getValueAt(raw, 0).toString());
            String sql = "select worker_id,first_name,last_name,worker_phone,worker_add,birth_date,email,contract_id,job_title from workers where worker_id='" + tableClick + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("first_name");
                UserFirstNameText.setText(add1);
                String add2 = rs.getString("last_name");
                UserLastNameText.setText(add2);
                String add3 = rs.getString("worker_phone");
                UserPhoneText.setText(add3);
                String add4 = rs.getString("job_title");
                UserJobTitleText.setText(add4);
                String add5 = rs.getString("email");
                UserEmailText.setText(add5);                    
            }                                         
         }
          catch (Exception e){
    JOptionPane.showMessageDialog(null,e);
    
          }
    }//GEN-LAST:event_AddUserTableMouseClicked

    private void UserFirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFirstNameTextActionPerformed

    private void UserLastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserLastNameTextActionPerformed

    private void UserPhoneTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPhoneTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPhoneTextActionPerformed

    private void UserJobTitleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserJobTitleTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserJobTitleTextActionPerformed

    private void UserEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserEmailTextActionPerformed

    private void UserAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserAddButtonActionPerformed
      
      int ans=JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Give" +UserFirstNameText.getText()+" "+UserLastNameText.getText()+" Selected Permission ?", "Warning!", JOptionPane.YES_NO_OPTION);
      if(ans==0) {
         try {

            String sql = "Insert into users (password,user_name,user_type) values(?,?,?)";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1, UserPasswordText.getText());
            pst.setString(2, UserNameText.getText());
            pst.setInt(3, UserPermissionChoise.getSelectedIndex());
       
            pst.execute();
            JOptionPane.showMessageDialog(null, "User Has Been Given Permission");
            }
        
        catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
       }
      if (ans==1) {}
    }//GEN-LAST:event_UserAddButtonActionPerformed

    private void UserClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserClearButtonActionPerformed
        UserFirstNameText.setText("");
        UserLastNameText.setText("");
        UserPhoneText.setText("");
        UserJobTitleText.setText("");
        UserEmailText.setText("");
        UserNameText.setText("");
        UserPasswordText.setText("");
        
    }//GEN-LAST:event_UserClearButtonActionPerformed

    private void usersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersButtonActionPerformed
        projectsTab.setVisible(false);
        reportsTab.setVisible(false);
        usersTab.setVisible(true);
        user_update_table();
    }//GEN-LAST:event_usersButtonActionPerformed

    private void QuantityChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityChangeButtonActionPerformed
        QuantityChange qc = new QuantityChange();
        qc.setVisible(true);
    }//GEN-LAST:event_QuantityChangeButtonActionPerformed

    private void UserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameTextActionPerformed

    private void UserPasswordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPasswordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPasswordTextActionPerformed

    private void UserPermissionChoiseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserPermissionChoiseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPermissionChoiseMouseClicked

    private void genRepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genRepButtonActionPerformed
  Document doc = new Document();
  PdfWriter docWriter = null;
  DecimalFormat df = new DecimalFormat("0.00");
  Date d = Calendar.getInstance().getTime();
  
  try {
  
   //special font sizes
   Font bfBold12 = new Font(FontFamily.TIMES_ROMAN, 12, Font.BOLD, new BaseColor(0, 0, 0)); 
   Font bf12 = new Font(FontFamily.TIMES_ROMAN, 12); 
 
   DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
   Date date = new Date();
   //file path
   String dt=dateFormat.format(date);
   String path = "C:\\Users\\Adi\\Documents\\NetBeansProjects\\Projct\\Yatzig\\src\\" + "Project Report- " + dt + ".pdf";   
   docWriter = PdfWriter.getInstance(doc , new FileOutputStream(path));
   
   //document header attributes
   doc.addCreationDate();
   doc.setPageSize(PageSize.LETTER);
  
   //open document
   doc.open();

   
   //create a paragraph
   DateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy");
   String sd2= dateFormat2.format(pBeginDateChooser.getDate());
   String ed2=dateFormat2.format(pEndDateChooser.getDate());
   Image image = Image.getInstance("src/Images/logo for pdf.png");
   Font font1 = new Font(Font.FontFamily.HELVETICA  , 25, Font.BOLD);
   Paragraph paragraph = new Paragraph();
   Paragraph paragraph2 = new Paragraph("This report was generated by " +loginGUI.username+ " at "+d+
    "\nYou can see all projects from "+sd2+" to "+ed2);
   image.setAlignment(Image.RIGHT);
   doc.add(image);
   
   //specify column widths
   float[] columnWidths = {2f, 2f, 2f, 2f, 2f};
   //create PDF table with the given widths
   PdfPTable table = new PdfPTable(columnWidths);
   // set table width a percentage of the page width
   table.setWidthPercentage(100f);

   //insert column headings
   insertCell(table, "Project ID", Element.ALIGN_CENTER, 1, bfBold12);
   insertCell(table, "Project Name", Element.ALIGN_CENTER, 1, bfBold12);
   insertCell(table, "Start Date", Element.ALIGN_CENTER, 1, bfBold12);
   insertCell(table, "Due Date", Element.ALIGN_CENTER, 1, bfBold12);
   insertCell(table, "Status", Element.ALIGN_CENTER, 1, bfBold12);
   table.setHeaderRows(1);

   //insert an empty row
  /* insertCell(table, "", Element.ALIGN_LEFT, 4, bfBold12);*/
   //create section heading by cell merging
  /* insertCell(table, "New York Orders ...", Element.ALIGN_LEFT, 4, bfBold12);*/
   /*double orderTotal, total = 0;*/
   
   String add1,add2,add3,add4,add5;
   DateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
   String sd= dateFormat1.format(pBeginDateChooser.getDate());
   String ed=dateFormat1.format(pEndDateChooser.getDate());
   try {
            String sql = "select project_id,project_name,start_date,due_date,status from projects where due_date >= '"+sd+"' and due_date <= '"+ed+"' and start_date >= '"+sd+"'and start_date <= '"+ed+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) { 
                 add1 = rs.getString("project_id");
                 add2 = rs.getString("project_name");
                 add3 = dateFormat.format(rs.getDate("start_date"));
                 add4 = dateFormat.format(rs.getDate("due_date"));
                 add5 = rs.getString("status");   
                 insertCell(table,add1 , Element.ALIGN_CENTER, 1, bf12);
                 insertCell(table,add2 , Element.ALIGN_CENTER, 1, bf12);
                 insertCell(table,add3 , Element.ALIGN_CENTER, 1, bf12);
                 insertCell(table,add4 , Element.ALIGN_CENTER, 1, bf12);
                 insertCell(table,add5 , Element.ALIGN_CENTER, 1, bf12);

        }                                         
         }
          catch (Exception e){
    JOptionPane.showMessageDialog(null,e);
    
        }

   //add the PDF table to the paragraph 
   paragraph2.add(table);
   
   // add the paragraph to the document
   doc.add(new Paragraph("\nProject Status Report "+ dt + "\n", font1));
   doc.add(paragraph2);
  }
  catch (DocumentException dex)
  {
   dex.printStackTrace();
  }    
  catch (Exception ex)
  {
   ex.printStackTrace();
  }
  finally
  {
   if (doc != null){
    //close the document
    doc.close();
    JOptionPane.showMessageDialog(null, "Report Generated!");
   }
   if (docWriter != null){
    //close the writer
    docWriter.close();
   }
  }        
    }//GEN-LAST:event_genRepButtonActionPerformed

    private void Show_report_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_report_ButtonActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        String dt=dateFormat.format(date);
        filename_show_report = "C:\\Users\\Felix\\Documents\\NetBeansProjects\\Projct\\Yatzig\\src\\" + "Project Report- " + dt + ".pdf" ;
        try {

            Desktop.getDesktop().open(new File(filename_show_report));
        }

        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"The Report Generetad Wasn't Found");
        }
    }//GEN-LAST:event_Show_report_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome3().setVisible(true);
            }
        });
    }

       
        private void update_Status_ProjTable(){
        try {
            String sql = "select project_id as 'Project ID',project_name as 'Project Name',start_date as 'Start Date',due_date as 'Due Date',status as 'Status',comments as 'Comments' from projects";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            projUpTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
        
        private void update_Search_ProjTable(){
        try {
            String sql = "select project_id as 'Project ID',project_name as 'Project Name',start_date as 'Start Date',due_date as 'Due Date',status as 'Status',comments as 'Comments' from projects";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);
            projSearchTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
            
        private void user_update_table(){
        try{
                 String sql = "select worker_id as 'Worker ID',first_name as 'First Name',last_name as 'Last Name',worker_phone as 'Phone',worker_add as 'Address', birth_date as 'Birthdate', email as 'Email',contract_id as 'Contract ID',job_title as 'Job Title' from workers";
                 pst=conn.prepareStatement(sql);
                 rs=pst.executeQuery(sql);
                 AddUserTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    /**
     *
     * @return
     */
    public void setAlertIconVisible() {
        AlertIcon.setVisible(false);
    }
    
    public void setButtonEnable() {
        QuantityChangeButton.setEnabled(false);
    }
    
  private void insertCell(PdfPTable table, String text, int align, int colspan, Font font){
  
  //create a new cell with the specified Text and Font
  PdfPCell cell = new PdfPCell(new Phrase(text.trim(), font));
  //set the cell alignment
  cell.setHorizontalAlignment(align);
  //set the cell column span in case you want to merge two or more cells
  cell.setColspan(colspan);
  //in case there is no text and you wan to create an empty row
  if(text.trim().equalsIgnoreCase("")){
   cell.setMinimumHeight(10f);
  }
  //add the call to the table
  table.addCell(cell);
  
 }

                        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProjectPanel;
    private javax.swing.JPanel AddUserPanel;
    private javax.swing.JTable AddUserTable;
    private javax.swing.JLabel AlertIcon;
    private javax.swing.JLabel EnterYourSearchLabel10;
    private javax.swing.JLabel EnterYourSearchLabel9;
    private javax.swing.JPanel HistoryPanel;
    private javax.swing.JLabel ProjectCommentsLabel;
    private javax.swing.JLabel ProjectDuedateLabel;
    private javax.swing.JLabel ProjectIDLabel;
    private javax.swing.JLabel ProjectNameLabel;
    private javax.swing.JPanel ProjectReportPanel;
    private javax.swing.JLabel ProjectStartdateLabel;
    private javax.swing.JButton QuantityChangeButton;
    private javax.swing.JPanel SearchProjectPanel;
    private javax.swing.JButton Show_report_Button;
    private javax.swing.JPanel StatusProjectPanel;
    private javax.swing.ButtonGroup SupplierButtonGroup;
    private javax.swing.JButton UserAddButton;
    private javax.swing.JButton UserClearButton;
    private javax.swing.JLabel UserDetailsLabel;
    private javax.swing.JLabel UserEmailLabel;
    private javax.swing.JTextField UserEmailText;
    private javax.swing.JLabel UserFirstNameLabel;
    private javax.swing.JTextField UserFirstNameText;
    private javax.swing.JLabel UserJobTitleLabel;
    private javax.swing.JTextField UserJobTitleText;
    private javax.swing.JLabel UserLastNameLabel;
    private javax.swing.JTextField UserLastNameText;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UserNameText;
    private javax.swing.JLabel UserPasswordLabel;
    private javax.swing.JTextField UserPasswordText;
    private java.awt.Choice UserPermissionChoise;
    private javax.swing.JLabel UserPermissionLabel;
    private javax.swing.JLabel UserPhoneLabel;
    private javax.swing.JTextField UserPhoneText;
    private javax.swing.JLabel WorkerDetailsLabel;
    private javax.swing.JLabel background_green11;
    private javax.swing.JLabel background_green12;
    private javax.swing.JLabel background_green13;
    private javax.swing.JLabel background_green14;
    private javax.swing.JLabel background_green15;
    private javax.swing.JLabel background_green16;
    private javax.swing.JLabel background_green4;
    private javax.swing.JToggleButton genRepButton;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logoutButton;
    private com.toedter.components.JSpinField monthRepjSpin;
    private com.toedter.calendar.JDateChooser pBeginDateChooser;
    private com.toedter.calendar.JDateChooser pEndDateChooser;
    private javax.swing.JButton projAddButton;
    private javax.swing.JButton projClearButton;
    private javax.swing.JTextArea projComUptxt;
    private javax.swing.JTextArea projDesctxt;
    private com.toedter.calendar.JDateChooser projDueDate;
    private javax.swing.JRadioButton projIDRadioButton;
    private javax.swing.JRadioButton projIDRadioButton1;
    private javax.swing.JTextField projIDtxt;
    private javax.swing.JRadioButton projNameRadioButton;
    private javax.swing.JRadioButton projNameRadioButton1;
    private javax.swing.JTextField projNametxt;
    private javax.swing.JButton projRefreshSearchButton;
    private javax.swing.JButton projSearchButton;
    private javax.swing.JTable projSearchTable;
    private javax.swing.JTextField projSearchUptxt;
    private javax.swing.JTextField projSearchtxt;
    private com.toedter.calendar.JDateChooser projStartDate;
    private com.toedter.calendar.JDateChooser projUpDueDate;
    private javax.swing.JButton projUpRefreshButton;
    private javax.swing.JButton projUpSearchButton;
    private javax.swing.JButton projUpStatusButton;
    private java.awt.Choice projUpStatusChoice;
    private javax.swing.JTable projUpTable;
    private javax.swing.JButton projectsButton;
    private javax.swing.JTabbedPane projectsTab;
    private javax.swing.JTextField repItemIDtxt;
    private javax.swing.JButton reportsButton;
    private javax.swing.JTabbedPane reportsTab;
    private javax.swing.ButtonGroup searchGroup;
    private javax.swing.JButton usersButton;
    private javax.swing.JTabbedPane usersTab;
    private com.toedter.components.JSpinField yearRepjSpin;
    // End of variables declaration//GEN-END:variables

}
